// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import PostFormController from "./post_form_controller"
application.register("post-form", PostFormController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import SettingsTabsController from "./settings_tabs_controller"
application.register("settings-tabs", SettingsTabsController)

import ScrapersController from "./scrapers_controller"
application.register("scrapers", ScrapersController)

import ImportController from "./import_controller"
application.register("import", ImportController)
